# Generated by Django 5.1.3 on 2024-12-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bonus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True, help_text='First Login flag to show the guide or not', verbose_name='First Login'),
        ),
    ]
