# Generated by Django 5.1.3 on 2024-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_of_deposit',
            field=models.CharField(blank=True, choices=[('Challenge', 'Challenge'), ('Task', 'Task'), ('Validation', 'Validation'), ('Referral', 'Referral')], null=True, verbose_name='Deposit Type'),
        ),
    ]
