# Generated by Django 5.1.3 on 2024-12-06 18:04

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='example',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Other/file-examples/', validators=[tasks.models.validate_example_file_extension], verbose_name='Example File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ImageField(upload_to='Other/tasks-photos/', validators=[tasks.models.validate_photo_file_extension], verbose_name='Photo'),
        ),
    ]
