# Generated by Django 5.1.3 on 2024-12-12 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_example_alter_task_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='raterecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
