# Generated by Django 5.1.3 on 2024-12-17 19:39

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_raterecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_instruction',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Other/tasks-instructions/', validators=[tasks.models.validate_pdf_file_extension], verbose_name='Task instruction'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Task description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='validation_limit',
            field=models.IntegerField(default=3, verbose_name='Validation Limit for one completion'),
        ),
    ]
