# Generated by Django 5.1.3 on 2024-12-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_task_instruction_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, help_text='Start time to postpone starting', null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='validation_limit',
            field=models.IntegerField(default=3, help_text='Validation Limit for one completion', verbose_name='Validation Limit'),
        ),
    ]
