# Generated by Django 5.1.3 on 2024-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_start_time_alter_task_validation_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_paused',
            field=models.BooleanField(default=False, verbose_name='Task Paused?'),
        ),
        migrations.AddField(
            model_name='task',
            name='validation_paused',
            field=models.BooleanField(default=False, verbose_name='Validation Paused?'),
        ),
    ]
