# Generated by Django 5.1.3 on 2025-03-22 12:28

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_task_paused_task_validation_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.PositiveIntegerField(validators=[tasks.models.exempt_zero], verbose_name='Reward'),
        ),
    ]
