# Generated by Django 5.1.3 on 2025-03-24 14:31

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='validation_reward',
            field=models.PositiveIntegerField(validators=[tasks.models.exempt_zero], verbose_name='Validation Reward'),
        ),
    ]
