# Generated by Django 5.1.3 on 2024-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='avatar',
            field=models.ImageField(upload_to='Other/challenge-photos/', verbose_name='Photo'),
        ),
    ]
